### ISSUE TITLE
Moondeck and buddy status: Exception

### ISSUE THREAD

**Issue by OriginalCubes** [FrogTheFrog/moondeck-buddy#30]
After Updating both Moondeck to 1.6.0 and Moondeck buddy to 1.5, the two no longer pair. The status in the steam deck shows "Exception".

I downgraded SD to 1.5.9 and SD buddy to 1.4.2 and I immediately got the prompt to pair again and everything works fine. Then I tried to forget the host then uninstall Steamdeck, then reinstall 1.6.0, and reload it, but I keep getting the same "exception" error.

I enabled logging and only got this:

> 09:23:48.187] INFO     buddy.utils: Log location: "C:/Users/***/AppData/Local/Programs/MoonDeckBuddy/bin/moondeckbuddy.log"
> [09:23:48.187] INFO     buddy.main: startup.
> [09:23:48.281] INFO     buddy.server: Server started listening at port 59999
> [09:23:48.281] INFO     buddy.main: startup finished.
> [09:23:48.281] DEBUG    buddy.os: Steam exec path: "c:/videogames win10/steam/steam.exe"
> [09:23:48.282] DEBUG    buddy.os: Steam is running!
> [09:23:48.282] DEBUG    buddy.os: Handling Steam start.

Moondeck on its own work fine, same with remote play.

**Comment by FrogTheFrog** [comment]
I really need the log from SteamDeck. Can you post '/tmp/moondeck.log'?

**Comment by OriginalCubes** [comment]
Of course, here you go:

<details>
2023-04-09 10:15:32,423 INFO -> get_user_settings(args=(<class '_.Plugin'>,))
2023-04-09 10:15:32,425 INFO <- get_user_settings(...): {'version': 10, 'clientId': 'e8e5d11b-dfbb-4998-9d9a-9acbc0f0ed8e', 'currentHostId': '7D2DA48E-7E5A-160D-4918-55BAEE98B178', 'gameSession': {'autoApplyAppId': True, 'resumeAfterSuspend': False}, 'buttonPosition': {'horizontalAlignment': 'top', 'verticalAlignment': 'right', 'offsetX': '', 'offsetY': '', 'offsetForHltb': False}, 'buttonStyle': {'showFocusRing': False, 'theme': 'Clean'}, 'hostSettings': {'7D2DA48E-7E5A-160D-4918-55BAEE98B178': {'buddyPort': 59999, 'address': '192.168.0.134', 'staticAddress': False, 'hostName': 'Matts-PC', 'mac': '04:42:1a:2c:01:14', 'closeSteamOnceSessionEnds': False, 'resolution': {'automatic': True, 'appResolutionOverride': 'CustomResolution', 'passToBuddy': True, 'passToMoonlight': True, 'useCustomDimensions': False, 'selectedDimensionIndex': -1, 'defaultBitrate': None, 'dimensions': []}, 'hostApp': {'selectedAppIndex': -1, 'apps': []}}}}
2023-04-09 10:15:32,633 INFO -> get_buddy_status(args=(<class '_.Plugin'>,), kwargs={'address': '192.168.0.134', 'buddy_port': 59999, 'client_id': 'e8e5d11b-dfbb-4998-9d9a-9acbc0f0ed8e', 'timeout': 1})
2023-04-09 10:15:32,633 ERROR Unhandled exception
Traceback (most recent call last):
  File "/home/deck/homebrew/plugins/moondeck/main.py", line 82, in get_buddy_status
    async with BuddyClient(address, buddy_port, client_id, timeout) as client:
  File "/home/deck/homebrew/plugins/moondeck/python/lib/buddyclient.py", line 80, in __aenter__
    self.__requests = await BuddyRequests(self.address, self.port, self.client_id, self.timeout).__aenter__()
  File "/home/deck/homebrew/plugins/moondeck/python/lib/buddyrequests.py", line 78, in __aenter__
    ssl_context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=cafile)
  File "ssl.py", line 765, in create_default_context
FileNotFoundError: [Errno 2] No such file or directory
2023-04-09 10:15:32,634 INFO <- get_buddy_status(...): Exception
2023-04-09 10:15:32,635 INFO -> find_host(args=(<class '_.Plugin'>,), kwargs={'host_id': '7D2DA48E-7E5A-160D-4918-55BAEE98B178', 'timeout': 1})
2023-04-09 10:15:32,657 INFO <- find_host(...): {'address': '192.168.0.134', 'hostName': 'Matts-PC', 'mac': '04:42:1a:2c:01:14', 'uniqueId': '7D2DA48E-7E5A-160D-4918-55BAEE98B178'}
2023-04-09 10:21:28,693 INFO -> get_user_settings(args=(<class '_.Plugin'>,))
2023-04-09 10:21:28,693 INFO <- get_user_settings(...): {'version': 10, 'clientId': 'e8e5d11b-dfbb-4998-9d9a-9acbc0f0ed8e', 'currentHostId': '7D2DA48E-7E5A-160D-4918-55BAEE98B178', 'gameSession': {'autoApplyAppId': True, 'resumeAfterSuspend': False}, 'buttonPosition': {'horizontalAlignment': 'top', 'verticalAlignment': 'right', 'offsetX': '', 'offsetY': '', 'offsetForHltb': False}, 'buttonStyle': {'showFocusRing': False, 'theme': 'Clean'}, 'hostSettings': {'7D2DA48E-7E5A-160D-4918-55BAEE98B178': {'buddyPort': 59999, 'address': '192.168.0.134', 'staticAddress': False, 'hostName': 'Matts-PC', 'mac': '04:42:1a:2c:01:14', 'closeSteamOnceSessionEnds': False, 'resolution': {'automatic': True, 'appResolutionOverride': 'CustomResolution', 'passToBuddy': True, 'passToMoonlight': True, 'useCustomDimensions': False, 'selectedDimensionIndex': -1, 'defaultBitrate': None, 'dimensions': []}, 'hostApp': {'selectedAppIndex': -1, 'apps': []}}}}
2023-04-09 10:21:28,895 INFO -> get_buddy_status(args=(<class '_.Plugin'>,), kwargs={'address': '192.168.0.134', 'buddy_port': 59999, 'client_id': 'e8e5d11b-dfbb-4998-9d9a-9acbc0f0ed8e', 'timeout': 1})
2023-04-09 10:21:28,896 ERROR Unhandled exception
Traceback (most recent call last):
  File "/home/deck/homebrew/plugins/moondeck/main.py", line 82, in get_buddy_status
    async with BuddyClient(address, buddy_port, client_id, timeout) as client:
  File "/home/deck/homebrew/plugins/moondeck/python/lib/buddyclient.py", line 80, in __aenter__
    self.__requests = await BuddyRequests(self.address, self.port, self.client_id, self.timeout).__aenter__()
  File "/home/deck/homebrew/plugins/moondeck/python/lib/buddyrequests.py", line 78, in __aenter__
    ssl_context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH, cafile=cafile)
  File "ssl.py", line 765, in create_default_context
FileNotFoundError: [Errno 2] No such file or directory
2023-04-09 10:21:28,896 INFO <- get_buddy_status(...): Exception
2023-04-09 10:21:28,898 INFO -> find_host(args=(<class '_.Plugin'>,), kwargs={'host_id': '7D2DA48E-7E5A-160D-4918-55BAEE98B178', 'timeout': 1})
2023-04-09 10:21:28,915 INFO <- find_host(...): {'address': '192.168.0.134', 'hostName': 'Matts-PC', 'mac': '04:42:1a:2c:01:14', 'uniqueId': '7D2DA48E-7E5A-160D-4918-55BAEE98B178'}
</details>

**Comment by FrogTheFrog** [comment]
Ugh, stupid file did not get uploaded again it seems. Could you try switching to the testing store and getting that version?

**Comment by Maz111111** [comment]
1.6.0-b35cbb3 seems to work

**Comment by OriginalCubes** [comment]
1.6.0-b35cbb3 Worked like a charm! The update seems to have also fixed a bug where steam's UI would crash every time I launched a game through moondeck and I had to 'refresh' it.

I also tested the new sunshine feature, since it wasn't working with the 'exception' bug, and it's amazing, thank you so much!

**Comment by Enuil83** [comment]
Hello,

When I switch over to the testing store. I only see version 1.5.9 am I missing something?

**Comment by FrogTheFrog** [comment]
> Hello,
> 
> When I switch over to the testing store. I only see version 1.5.9 am I missing something?

I think you need to click the dropdown menu as I can see it's still in testing store (https://testing.deckbrew.xyz/)

**Comment by Enuil83** [comment]
> Hello,
> 
> When I switch over to the testing store. I only see version 1.5.9 am I missing something?

Disregard I'm an idiot. Have to go to the actual store to find the alternative versions 🙄

**Comment by XenHat** [comment]
I'm glad I found this issue. I've been really confused about seeing "Exception" on the moondeck stable branch and not knowing what I broke.

**Comment by XenHat** [comment]
in any case, it is working now. 🥳 
![20230411_024410](https://user-images.githubusercontent.com/980408/231078074-4b77054c-365b-4938-b060-f6fc54af21a2.jpg)

I sleep now
